image: "ruby:2.6"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v  # Print out ruby version for debugging
  - gem install bundler
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rspec:
  script:
    - rspec spec

